### ISSUE TITLE
As an admin, I should be able to create an account for myself

### ISSUE THREAD

**Issue by govindkrjoshi** [nilenso/winter-onboarding-2021#27]
On sign up, the user should be an admin by default. 

Other roles cannot signup without an invite link

**Comment by shhivam** [comment]
Sign up process for:

**Admin**

Anyone can sign up, if the email they entered is not already invited, their default role would be `admin`

Data needed for sign up:
1. Email: email must be in the right format. _required_
2. Password: min length of 10 characters _required_
3. Confirm password: should be same as the `Password` field _required_
4. Name: String, _required_

After successfully signing up, they should be redirected to login page.


**Fleet manager**
One can only sign up as fleet manager via a special link sent by an `Admin`
When someone opens the invite link, they should be asked:

1. Password: min length of 10 characters
2. Confirm password: should be same as the `Password` field
3. Name: String, _required_
After successfully signing up, they should be redirected to login page.


**Driver**
One can only sign up as a driver via a special link sent by an `Admin`
When someone opens the invite link, they should be asked:

1. Password: min length of 10 characters
2. Confirm password: should be same as the `Password` field
3. Name: String, _required_
After successfully signing up, they should be redirected to login page.
