### ISSUE TITLE
As an user, I should be able to login using email and password

### ISSUE THREAD

**Issue by govindkrjoshi** [nilenso/winter-onboarding-2021#28]

**Comment by yogirajh007** [comment]
- There should be multiple points from which the user could log into the application. Like a login button on the landing page of the application. 
- On some protected pages, it will be required for the user to be logged in. On such pages, a login modal will open upon a user visit. 
- The login modal/form should have fields for emailID and password. Also, a _forgot password_ button/link could be provided.

**Comment by shhivam** [comment]
Some other points I forgot to mention:
1. Successful state: As a developer, I dont know which URL or what I will be redirected to after successful login.
2. Error state: How many unsuccessful tries? What will be the error message like?
