### ISSUE TITLE
As an admin, I should be able see the list of the fleets

### ISSUE THREAD

**Issue by govindkrjoshi** [nilenso/winter-onboarding-2021#29]
List all the fleets that an admin has created. 
The list should be table with columns
- Fleet Name
- Manager(s) Name (If there are multiple managers then a small button to view all the managers name on click, view the mock design for reference) 
- A button to view more(which would redirect to a page to show all the details of a fleet, like all the cabs associated with fleet)

There would be a button at the top of page to create a new fleet.
The list page should have pagination (5, 10 15 fleets per page)

![ListFleets](https://user-images.githubusercontent.com/36623306/145153488-90fc56a0-e95b-4604-86f5-cc520f7848eb.png)

**Comment by alishamohanty** [comment]
Sub tasks
----------
1. Create model for the `Fleet`
2. Relationship between fleet and user (keep in mind different role of users)
3. To write migration for the same
4. Implement the view for the list fleet page( in the mock ui above).
