### ISSUE TITLE
As an admin, I can send an invite link to other users, to ask them to join a organisation

### ISSUE THREAD

**Issue by govindkrjoshi** [nilenso/winter-onboarding-2021#31]
We need an invitations page that is visible only to admins. Invitations can be created by admins to add other admins, managers and drivers to the organisation. This page should also list existing invites.

- Invitations will be valid until expiry time
- Role of the created account will be determined by the link used to create the account
- Only a limited number of accounts can be created using an invite

To create an invitation, we need a form which takes:
- Role (Driver/Manager/Admin) as a dropdown
- Accounts allowed (default = 1)
- Validity (of the invite) in days

Below the form, we must show existing invites. Use the format below.

| Code      | Created by           | Valid until    | Accounts created |
|-----------|----------------------|----------------|------------------|
| A332X3GHE | Ravi Chandra Padmala | 26th May 2022  |       4/10       |
| X3GHEA332 | Yogiraj Hendre       | 6th April 2022 |       1/1        |
| HC834XXEA | Govind Joshi         | 9th June 2022  |       0/1        |

- The code should be the link that can be shared to invite users
- The 'Accounts created' value should link to a page that shows users that were created via that link

**Comment by yogirajh007** [comment]
Some new endpoints are to be created- 
GET - /invites - Which will render a page which contains the invites list and the new-invite form
POST - /invites - To create a new invite 
GET - /invites/invite-id - Which will list users who have signed up using the link


The link could be of this form - 
https://base_url/user/signup?invite-code=ABCDEFG

**Comment by yogirajh007** [comment]
A `invitations` table could be created which has following columns-

id | invite_code      | created_by           | valid_until    | usage_remaining | role | status|
--------|-----------|----------------------|----------------|------------------|-----|------|

- `id` UUID - Unique ID for invites
- `invite-code` TEXT - Unique random code
- `created_by` UUID - reference to the users table. 
- `valid-untill` TIMESTAMP - of last second of day
- `usage_remaining` INTEGER - representing number of usages left
- `role` TEXT - Role for which the invite link is valid for
- `status` TEXT - Status of the link - Which could be changed (Future addition)

**Comment by alishamohanty** [comment]
![Screenshot 2022-01-11 at 6 31 56 PM](https://user-images.githubusercontent.com/36623306/148947256-3290c1de-c3e5-4b3c-a523-d859e1cccda1.png)
