### ISSUE TITLE
As a driver & fleet manager, I want to be able to create an account via the invite link

### ISSUE THREAD

**Issue by shhivam** [nilenso/winter-onboarding-2021#36]
URL  `/users/signup`

**Fleet manager**
One can only sign up as fleet manager via a special link sent by an Admin
When someone opens the invite link, they should be asked:

Password: min length of 10 characters
Confirm password: should be same as the Password field
Name: String, required
Email: Pre-filled and user cant change it
After successfully signing up, they should be redirected to login page.

**Driver**
One can only sign up as a driver via a special link sent by an Admin
When someone opens the invite link, they should be asked:

Password: min length of 10 characters
Confirm password: should be same as the Password field
Name: String, required
Email: Pre-filled and user cant change it
After successfully signing up, they should be redirected to login page.

**Comment by alishamohanty** [comment]
- When the to-be-signed in user enters the url 
`https://base_url/user/signup?invite-code=ABCDEFG`
- Get the invite-code → check for details (if expired or right or not) If it valid, accept the details(like name, email, password) and create a user (with the role from the invitations table from the invitations code). After successful sign-up redirect to the login page.
(More details of the invitations table is shared here #31 )
